### ISSUE TITLE
Add pluck method and ids method

### ISSUE THREAD

**Issue by ricvillagrana** [ricvillagrana/easy-record#10]
1. Is needed for 1:N relationships have a `ids` method to get an array of ids.
2. Is needed to have a method `pluck` which take an attribute from the model lists and return an array of the attribute values.

- [x] Add `ids` method.
- [x] Add `pluck` method.

## Examples
```ruby
Person.ids # => ['8652b710-cb9f-0137-1165-2cbc32ad1b49', '8652b710-cb9f-0137-1165-2cbc32ad1b50']
```

```ruby
Person.pluck :name # => ['John', 'Mike', 'Robin', 'Hannah']
```

**Comment by nandhae** [comment]
@ricvillagrana I need clarifications on this. Where do you want it? Should we add these methods in associations.rb ? some directions would helps and i would be happy to pick this up.

**Comment by sathia27** [comment]
Hey @ricvillagrana,
I have raised pull requested. Added examples for those new methods. Let me know if there is anything required.
Please review and let me to know

**Comment by ricvillagrana** [comment]
Good job @sathia27, thank you.
