### ISSUE TITLE
Automatically add belongs_to attribute name to instance variables.

### ISSUE THREAD

**Issue by ricvillagrana** [ricvillagrana/easy-record#15]
Currently, is needed to have the `list_id` in the `attr_accessor`, but would be nice if we can avoid this and only passing the name in the `belongs_to`.
```ruby
class List < EasyRecord
  attr_accessor :name

  has_many :tasks, class_name: 'Task'
end

class Task < EasyRecord
  attr_accessor :name, :done, :list_id

  belongs_to :list, { class_name: 'List' }, :list_id
end
```

**Comment by sathia27** [comment]
@ricvillagrana can I take this up?

**Comment by ricvillagrana** [comment]
@sathia27, sure, all yours.

**Comment by sathia27** [comment]
@ricvillagrana I have given PR for this. Please review. Let me know if you feel there are any issues.
