### ISSUE TITLE
Change a method name

### ISSUE THREAD

**Issue by ricvillagrana** [ricvillagrana/easy-record#6]
Currently I have a method called `has_many_simple`, but I think that `has_many_directly` is a better name.

The method is in the [associations.rb](https://github.com/DianaS24/easy-record/blob/master/lib/easy_record/association.rb) file.

Feel free to suggest another name if you think is better.

**Comment by whiz25** [comment]
@ricvillagrana  I think ```has_many_directly``` is still good. I will look at it.

**Comment by nandhae** [comment]
Looks like it is not in progress and up for grabs. I'll raise a PR now if @whiz25 is not working on it.

**Comment by nandhae** [comment]
Raised a PR #8 , Please Review :)
